Repository codestates-seb/seb45_main_006, pull requests merged in 2023-08, with the labels that each got.

#9 [FE] 🎉 1) 프로젝트 세팅
  .github/ISSUE_TEMPLATE/bug_report.md
  client/.eslintrc.cjs
  client/.gitignore
  client/.npmrc
  client/.prettierrc
  client/README.md
  client/index.html
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/public/vite.svg
  client/src/App.tsx
  client/src/assets/react.svg
  client/src/container/ErrorPage.tsx
  client/src/container/Main.tsx
  client/src/feature/Global.ts
  client/src/index.css
  client/src/main.tsx
  client/src/vite-env.d.ts
  client/tailwind.config.js
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
Labels: [FE] 임정렬

#17 [FE] 💄 16 Header) 공통 컴포넌트인 헤더, 버튼 작업
  client/index.html
  client/public/icon_logo.png
  client/src/App.tsx
  client/src/assets/icon_logo.png
  client/src/component/common/Button.tsx
  client/src/component/common/Header.tsx
  client/src/container/Main.tsx
  client/src/container/MyPage.tsx
  client/src/index.css
  client/tailwind.config.js
  client/tsconfig.json
  client/vite.config.ts
Labels: [FE] 임정렬

#13 [BE]✨ 1) MemberCRUD, Postion, nicknameCheck
  server/.idea/.gitignore
  server/.idea/compiler.xml
  server/.idea/gradle.xml
  server/.idea/misc.xml
  server/.idea/modules.xml
  server/.idea/server.iml
  server/.idea/vcs.xml
  server/DevSquad/build.gradle
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/member/controller/MemberController.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/member/dto/MemberPostDto.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/member/dto/MemberProfileDto.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/member/entity/Member.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/member/entity/MemberProfile.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/member/mapper/MemberMapper.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/member/repository/MemberProfileRepository.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/member/repository/MemberRepository.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/member/service/MemberService.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/position/entity/Position.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/position/repository/PositionRepository.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/position/service/PositionService.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/utils/PageInfo.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/utils/PageResponseDto.java
  server/DevSquad/src/main/resources/application.properties
  server/DevSquad/src/main/resources/application.yml
Labels: [BE] 신동민

#14 [BE]✨ 2) add MemberDtoValid
  server/DevSquad/.gitignore
  server/DevSquad/build.gradle
  server/DevSquad/gradle/wrapper/gradle-wrapper.jar
  server/DevSquad/gradle/wrapper/gradle-wrapper.properties
  server/DevSquad/gradlew
  server/DevSquad/gradlew.bat
  server/DevSquad/settings.gradle
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/DevSquadApplication.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/member/controller/MemberController.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/member/dto/MemberPostDto.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/member/dto/MemberProfileDto.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/member/entity/Member.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/member/entity/MemberProfile.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/member/mapper/MemberMapper.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/member/repository/MemberProfileRepository.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/member/repository/MemberRepository.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/member/service/MemberService.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/position/entity/Position.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/position/repository/PositionRepository.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/position/service/PositionService.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/utils/PageInfo.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/utils/PageResponseDto.java
  server/DevSquad/src/main/resources/application.yml
  server/DevSquad/src/test/java/WOOMOOL/DevSquad/DevSquadApplicationTests.java
Labels: [BE] 신동민

#19 [BE] ✨ 6, 7) Project, Study CRUD
  server/DevSquad/build.gradle
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/projectBoard/controller/ProjectController.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/projectBoard/dto/ProjectDto.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/projectBoard/entity/Board.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/projectBoard/entity/Project.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/projectBoard/mapper/ProjectMapper.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/projectBoard/repository/ProjectRepository.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/projectBoard/service/ProjectService.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/studyBoard/controller/StudyController.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/studyBoard/dto/StudyDto.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/studyBoard/entity/Study.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/studyBoard/mapper/StudyMapper.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/studyBoard/repository/StudyRepository.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/studyBoard/service/StudyService.java
  server/DevSquad/src/main/resources/application.yml
Labels: [BE] 설주연
