Repository codestates-seb/seb45_main_006, pull requests merged in 2023-09, with the labels that each got.

#38 [FE] ✨ 18) 캐러셀 기능구현
  client/src/assets/main/board.svg
  client/src/assets/main/project.svg
  client/src/assets/main/study.svg
  client/src/component/main/CarouselCustomNavigation.tsx
  client/src/container/Main.tsx
  client/src/main.tsx
  client/tailwind.config.js
Labels: [FE] 이예진

#48 FE 💄 31) 회원가입 임시 폼 추가 및 회원관련 api 요청/응답 작성
  client/index.html
  client/src/App.tsx
  client/src/api/member/api.ts
  client/src/api/member/hook.ts
  client/src/api/member/memberKeyFactory.ts
  client/src/api/sign/api.ts
  client/src/api/sign/hook.ts
  client/src/api/sign/signKeyFactory.ts
  client/src/assets/icon_people.png
  client/src/component/common/Header.tsx
  client/src/container/Container.tsx
  client/src/container/sign/TempSignUp.tsx
  client/src/hook/useElementWidthAndHeight.ts
  client/src/index.css
  client/src/type/common.ts
  client/src/type/member/member.req.dto.ts
  client/src/type/member/member.res.dto.ts
  client/src/type/sign/sign.req.dto.ts
  client/src/type/sign/sign.res.dto.ts
Labels: [FE] 임정렬

#50 [FE] 👔 49) react-query 코드 피드백 반영
  client/src/App.tsx
  client/src/api/common/commonApi.ts
  client/src/api/common/todoTestApi.ts
  client/src/api/common/withAuthApi.ts
  client/src/api/constant.ts
  client/src/api/member/api.ts
  client/src/api/member/hook.ts
  client/src/api/member/memberKeyFactory.ts
  client/src/api/sign/api.ts
  client/src/api/sign/hook.ts
  client/src/api/todo/api.ts
  client/src/api/todo/hook.ts
  client/src/component/todo/ReadOrUpdateTodo.tsx
  client/src/container/sign/TempSignUp.tsx
  client/src/container/todo/CreateTodo.tsx
  client/src/type/member/member.req.dto.ts
  client/src/util/token-helper.ts
Labels: [FE] 임정렬

#51 [FE] ✏️15) 회원가입
  .vscode/launch.json
  client/src/App.tsx
  client/src/assets/font.png
  client/src/assets/github.png
  client/src/assets/google.png
  client/src/assets/progress_bar1.png
  client/src/assets/progress_bar2.png
  client/src/assets/progress_bar3.png
  client/src/container/SignUp.tsx
  client/src/feature/signup.ts
  client/tailwind.config.js
Labels: [FE] 손설희

#52 [FE] ✨ 41) 프로젝트 등록 페이지 기본 기능 & CSS
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/component/common/Button.tsx
  client/src/component/project/ProjectInput.tsx
  client/src/component/project/ProjectTextarea.tsx
  client/src/container/Main.tsx
  client/src/container/project/ProjectBoard.tsx
  client/src/container/project/ProjectRegister.tsx
  client/tailwind.config.js
Labels: [FE] 이예진

#47 [BE] :sparkles: 10) 정보게시판 유저조회기능 추가
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/board/repository/BoardRepository.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/comment/controller/CommentController.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/comment/dto/CommentDto.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/comment/mapper/CommentMapper.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/comment/service/CommentService.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/infoboard/controller/InfoBoardController.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/infoboard/repository/InfoBoardRepository.java
Labels: [BE] 오동석

#56 [FE] 🔧 54) 폴더구조 수정
  .vscode/launch.json
  client/.eslintrc.cjs
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/common/refreshToken.ts
  client/src/api/constant.ts
  client/src/api/member/api.ts
  client/src/api/member/hook.ts
  client/src/common-component/Button.tsx
  client/src/common-component/Header.tsx
  client/src/common-component/Pagination.tsx
  client/src/common-component/Typography.tsx
  client/src/container/Main.tsx
  client/src/container/layout/Layout.tsx
  client/src/container/main/Main.tsx
  client/src/container/main/component/CarouselCustomNavigation.tsx
  client/src/container/mypage/MyPage.tsx
  client/src/container/project/Board.tsx
  client/src/container/project/Register.tsx
  client/src/container/project/component/ProjectInput.tsx
  client/src/container/project/component/ProjectTextarea.tsx
  client/src/container/sign/SignUp.tsx
  client/src/container/sign/TempSignUp.tsx
  client/src/container/todo/CreateTodo.tsx
  client/src/container/todo/TodoDetail.tsx
  client/src/container/todo/TodoList.tsx
  client/src/container/todo/todo/ReadOrUpdateTodo.tsx
  client/src/container/todo/todo/TodoComponents.tsx
  client/src/container/todo/todo/TodoUserCard.tsx
  client/src/main.tsx
  client/src/type/member/member.req.dto.ts
  client/src/type/member/member.res.dto.ts
  client/tsconfig.json
  client/vite.config.ts
Labels: [FE] 임정렬, [FE] 이예진, [FE] 손설희

#62 FE 💄 61) sign 공통 컴포넌트
  client/src/App.tsx
  client/src/assets/sign/font.png
  client/src/assets/sign/github.png
  client/src/assets/sign/google.png
  client/src/assets/sign/icon_github.png
  client/src/assets/sign/icon_people.png
  client/src/assets/sign/progress_bar1.png
  client/src/assets/sign/progress_bar2.png
  client/src/assets/sign/progress_bar3.png
  client/src/common-component/Button.tsx
  client/src/common-component/Header.tsx
  client/src/common-component/Input.tsx
  client/src/common-component/Textarea.tsx
  client/src/common-component/Typography.tsx
  client/src/common-component/board/Input.tsx
  client/src/common-component/board/Textarea.tsx
  client/src/container/layout/Layout.tsx
  client/src/container/project/Register.tsx
  client/src/container/project/component/ProjectInput.tsx
  client/src/container/project/component/ProjectTextarea.tsx
  client/src/container/sign/SignUp.tsx
  client/src/container/sign/TempProfile.tsx
  client/src/container/sign/TempSignUp.tsx
  client/src/container/sign/component/SignButton.tsx
  client/src/container/sign/component/SignInput.tsx
  client/src/container/sign/component/SignLayout.tsx
  client/src/container/todo/TodoList.tsx
  client/src/container/todo/todo/TodoUserCard.tsx
  client/src/feature/Global.ts
  client/tailwind.config.js
Labels: [FE] 임정렬

#74 [FE] 💄 71) 전체 공통 컴포넌트 - 토스트,모달
  client/.gitignore
  client/package.json
  client/src/App.tsx
  client/src/common-component/Button.tsx
  client/src/common-component/Modal.tsx
  client/src/common-component/Toast.tsx
  client/src/common-component/ToastList.tsx
  client/src/common-component/mockData.ts
  client/src/container/sign/TempSignUp.tsx
  client/src/container/sign/component/SignInput.tsx
  client/src/container/sign/component/SignLayout.tsx
  client/src/container/todo/CreateTodo.tsx
  client/src/container/todo/todo/ReadOrUpdateTodo.tsx
  client/src/feature/Global.ts
  client/src/hook/useToast.ts
  client/src/type/common.ts
  client/src/type/member/member.res.dto.ts
  client/src/util/random-helper.ts
  client/tailwind.config.js
Labels: [FE] 임정렬

#78 [FE] 💄 75) 유저리스트 화면 (유저카드 + 유저 상세 모달)
  client/src/App.tsx
  client/src/api/common/withAuthApi.ts
  client/src/api/constant.ts
  client/src/api/member/api.ts
  client/src/api/member/hook.ts
  client/src/api/member/memberKeyFactory.ts
  client/src/api/sign/api.ts
  client/src/common-component/ToastList.tsx
  client/src/common-component/board/UserCard.tsx
  client/src/common-component/board/UserCardModal.tsx
  client/src/container/user/List.tsx
  client/src/hook/userScrollControl.ts
  client/src/type/member/member.req.dto.ts
  client/src/type/member/member.res.dto.ts
Labels: [FE] 임정렬

#83 [FE] 💄 76) 검색필터
  client/src/api/common/withAuthApi.ts
  client/src/api/member/hook.ts
  client/src/assets/icon_logo-text.png
  client/src/common-component/AutoCompletionTags.tsx
  client/src/common-component/Header.tsx
  client/src/common-component/Input.tsx
  client/src/common-component/Textarea.tsx
  client/src/common-component/Toast.tsx
  client/src/common-component/board/Input.tsx
  client/src/common-component/board/SearchFilters.tsx
  client/src/common-component/board/SearchInput.tsx
  client/src/common-component/board/Textarea.tsx
  client/src/common-component/board/UserCardModal.tsx
  client/src/common-component/mockData.ts
  client/src/container/layout/Layout.tsx
  client/src/container/project/Board.tsx
  client/src/container/project/Register.tsx
  client/src/container/sign/TempProfile1.tsx
  client/src/container/sign/component/SignButton.tsx
  client/src/container/sign/component/SignInput.tsx
  client/src/container/sign/component/SignLayout.tsx
  client/src/container/study/Board.tsx
  client/src/container/study/Register.tsx
  client/src/container/todo/CreateTodo.tsx
  client/src/container/todo/todo/ReadOrUpdateTodo.tsx
  client/src/container/user/List.tsx
  client/src/container/user/component/SearchFilter.tsx
  client/src/hook/useToast.ts
  client/src/type/common.ts
  client/tailwind.config.js
Labels: [FE] 임정렬

#82 [BE] ✨ 11) 댓글 및 게시판 API 설계
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/answer/controller/AnswerController.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/answer/dto/AnswerDto.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/answer/mapper/AnswerMapper.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/answer/service/AnswerService.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/comment/dto/CommentDto.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/comment/mapper/CommentMapper.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/infoboard/dto/InfoBoardDto.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/infoboard/entity/InfoBoard.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/infoboard/mapper/InfoBoardMapper.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/questionboard/dto/QuestionBoardDto.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/questionboard/mapper/QuestionBoardMapper.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/questionboard/service/QuestionBoardService.java
Labels: [BE] 오동석

#87 [FE] 🔧 43) 프로젝트 스터디 react query 세팅
  client/package-lock.json
  client/package.json
  client/src/api/constant.ts
  client/src/api/project/api.ts
  client/src/api/project/hook.ts
  client/src/api/project/projectKeyFactory.ts
  client/src/api/study/api.ts
  client/src/api/study/hook.ts
  client/src/api/study/studyKeyFactory.ts
  client/src/assets/bookmark_fill.svg
  client/src/assets/bookmark_unfill.svg
  client/src/container/main/Main.tsx
  client/src/container/project/Details.tsx
  client/src/container/project/Register.tsx
  client/src/container/project/component/BoardList.tsx
  client/src/container/project/component/DateChoice.tsx
  client/src/container/study/Details.tsx
  client/src/container/study/Register.tsx
  client/src/type/project/project.req.dto.ts
  client/src/type/project/project.res.dto.ts
  client/src/type/study/study.req.dto.ts
  client/src/type/study/study.res.dto.ts
  client/tsconfig.json
Labels: [FE] 이예진

#85 [FE] 💄 77) 자유게시판 등록
  client/src/App.tsx
  client/src/api/common/withAuthApi.ts
  client/src/api/constant.ts
  client/src/api/info/api.ts
  client/src/api/info/constant.ts
  client/src/api/info/hook.ts
  client/src/api/info/infoKeyFactory.ts
  client/src/api/member/api.ts
  client/src/common-component/MarkdownEditor.css
  client/src/common-component/MarkdownEditor.tsx
  client/src/common-component/board/BoardContent.tsx
  client/src/common-component/board/Dropdown.tsx
  client/src/common-component/mockData.ts
  client/src/container/info/Register.tsx
  client/src/container/info/component/RegisterForm.tsx
  client/src/hook/useCheckEmptyInput.ts
  client/src/type/info/common.ts
  client/src/type/info/info.req.dto.ts
  client/src/type/info/info.res.dto.ts
Labels: [FE] 임정렬

#93 [FE] 💄 93 회원가입 페이지 구성 완료
  client/src/App.tsx
  client/src/common-component/Header.tsx
  client/src/container/SignUp.tsx
  client/src/container/sign/SignUp.tsx
  client/src/container/sign/SignUp1.tsx
  client/src/container/sign/SignUp2.tsx
  client/src/container/sign/SignUp3.tsx
  package-lock.json
Labels: [FE] 손설희

#91 [FE] 💄 90) 자유게시판 조회
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/answer/api.ts
  client/src/api/answer/hook.ts
  client/src/api/comment/api.ts
  client/src/api/comment/hook.ts
  client/src/api/constant.ts
  client/src/api/info/api.ts
  client/src/api/info/constant.ts
  client/src/api/info/hook.ts
  client/src/api/member/api.ts
  client/src/api/member/hook.ts
  client/src/api/project/hook.ts
  client/src/api/question/api.ts
  client/src/api/question/hook.ts
  client/src/api/question/questionKeyFactory.ts
  client/src/api/study/hook.ts
  client/src/common-component/Button.tsx
  client/src/common-component/Input.tsx
  client/src/common-component/MarkdownEditor.css
  client/src/common-component/MarkdownEditor.tsx
  client/src/common-component/Textarea.tsx
  client/src/common-component/board/BoardContent.tsx
  client/src/common-component/board/Comment.tsx
  client/src/common-component/board/SearchInput.tsx
  client/src/common-component/board/Textarea.tsx
  client/src/container/info/Board.tsx
  client/src/container/info/Register.tsx
  client/src/container/info/component/InfoItem.tsx
  client/src/container/info/component/RegisterForm.tsx
  client/src/container/info/component/SearchFilter.tsx
  client/src/container/question/Register.tsx
  client/src/type/answer/answer.req.dto.ts
  client/src/type/answer/answer.res.dto.ts
  client/src/type/comment/comment.req.dto.ts
  client/src/type/comment/comment.res.dto.ts
  client/src/type/comment/common.ts
  client/src/type/info/common.ts
  client/src/type/info/info.req.dto.ts
  client/src/type/info/info.res.dto.ts
  client/src/type/member/member.res.dto.ts
  client/src/type/question/question.req.dto.ts
  client/src/type/question/question.res.dto.ts
  client/tailwind.config.js
Labels: [FE] 임정렬

#100 [FE] 💄 92) 자유게시판 댓글
  client/src/App.tsx
  client/src/api/common/withAuthApi.ts
  client/src/common-component/Header.tsx
  client/src/common-component/Toast.tsx
  client/src/common-component/ToastList.tsx
  client/src/common-component/Typography.tsx
  client/src/common-component/board/Comment.tsx
  client/src/container/info/Board.tsx
  client/src/container/info/Register.tsx
  client/src/container/info/component/InfoItem.tsx
  client/src/container/user/List.tsx
  client/src/feature/Global.ts
  client/src/hook/useCheckCurActivity.ts
  client/src/hook/useCheckUser.ts
  client/src/hook/useToast.ts
  client/src/type/comment/comment.res.dto.ts
  client/src/type/info/info.res.dto.ts
  client/src/util/token-helper.ts
Labels: [FE] 임정렬

#113 [BE] ✨ 111) 자유,질문,답변,댓글 페이지네이션
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/answer/controller/AnswerController.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/answer/entity/Answer.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/answer/mapper/AnswerMapper.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/answer/repository/AnswerRepository.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/answer/service/AnswerService.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/comment/controller/CommentController.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/comment/entity/Comment.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/comment/repository/CommentRepository.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/comment/service/CommentService.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/infoboard/controller/InfoBoardController.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/infoboard/dto/InfoBoardDto.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/infoboard/entity/InfoBoard.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/infoboard/mapper/InfoBoardMapper.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/infoboard/repository/InfoBoardRepository.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/infoboard/service/InfoBoardService.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/likes/controller/LikesController.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/likes/entity/Likes.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/likes/repository/LikesRepository.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/likes/service/LikesService.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/member/entity/MemberProfile.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/questionboard/controller/QuestionBoardController.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/questionboard/dto/QuestionBoardDto.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/questionboard/entity/QuestionBoard.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/questionboard/mapper/QuestionBoardMapper.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/questionboard/repository/QuestionBoardRepository.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/questionboard/service/QuestionBoardService.java
Labels: [BE] 오동석

#124 [BE] ✨ 111) 게시판 조회 차단 기능 추가
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/answer/controller/AnswerController.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/answer/entity/Answer.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/board/entity/Board.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/board/repository/BoardRepository.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/board/service/BoardService.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/comment/controller/CommentController.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/comment/entity/Comment.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/infoboard/controller/InfoBoardController.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/infoboard/entity/InfoBoard.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/infoboard/mapper/InfoBoardMapper.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/infoboard/service/InfoBoardService.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/projectboard/controller/ProjectController.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/projectboard/entity/Project.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/projectboard/mapper/ProjectMapper.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/projectboard/service/ProjectService.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/questionboard/controller/QuestionBoardController.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/questionboard/entity/QuestionBoard.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/questionboard/mapper/QuestionBoardMapper.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/questionboard/service/QuestionBoardService.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/studyboard/controller/StudyController.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/studyboard/service/StudyService.java
Labels: [BE] 오동석

#115 [FE] 💄 99 마이페이지 + 인증 (닉네임 중복 검사, 로그인 이메일 인증, 비밀번호 찾기 이메일 인증) hook 추가
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/auth/hook.ts
  client/src/api/member/api.ts
  client/src/api/member/hook.ts
  client/src/api/sign/hook.ts
  client/src/common-component/AutoCompletionTags.tsx
  client/src/common-component/board/Input.tsx
  client/src/common-component/project-study/Report.tsx
  client/src/container/info/component/InfoItem.tsx
  client/src/container/layout/Layout.tsx
  client/src/container/mypage/AuthUser.tsx
  client/src/container/mypage/MyPage.tsx
  client/src/container/mypage/component/NavItems.tsx
  client/src/container/mypage/component/TabItems.tsx
  client/src/container/mypage/component/UserBlock.tsx
  client/src/container/mypage/component/UserInfo.tsx
  client/src/container/mypage/component/UserPw.tsx
  client/src/container/project/Register.tsx
  client/src/container/sign/FindPw.tsx
  client/src/container/sign/SignUp2.tsx
  client/src/container/user/component/UserActivity.tsx
  client/src/container/user/component/UserCardModal.tsx
  client/src/feature/Global.ts
  client/src/hook/useCheckAuth.ts
  client/src/type/member/member.req.dto.ts
  client/src/type/member/member.res.dto.ts
  client/tailwind.config.js
Labels: [FE] 임정렬

#126 [FE] 👔 58) 프로젝트 스터디 api 연동 2차
  client/src/App.tsx
  client/src/api/project/api.ts
  client/src/common-component/project-study/Report.tsx
  client/src/container/main/component/CarouselCustomNavigation.tsx
  client/src/container/main/component/ProjectList.tsx
  client/src/container/project/Details.tsx
  client/src/container/project/Register.tsx
  client/src/container/project/component/BoardList.tsx
  client/src/container/study/Details.tsx
  client/src/container/study/Register.tsx
  client/src/container/study/component/BoardList.tsx
  client/src/type/project/project.res.dto.ts
Labels: [FE] 이예진

#128 [FE] 127) 🐛 타입 관련 에러 수정 및 🔥 불필요한 타입 / console.log 삭제
  client/src/api/answer/hook.ts
  client/src/api/auth/hook.ts
  client/src/api/chat/hook.ts
  client/src/api/comment/hook.ts
  client/src/api/info/hook.ts
  client/src/api/member-activity/hook.ts
  client/src/api/member/hook.ts
  client/src/api/project/api.ts
  client/src/api/project/hook.ts
  client/src/api/question/hook.ts
  client/src/api/sign/api.ts
  client/src/api/sign/hook.ts
  client/src/api/study/hook.ts
  client/src/common-component/Header.tsx
  client/src/container/chat/ChatBot.tsx
  client/src/container/chat/component/ChatRoomItem.tsx
  client/src/container/main/component/ChangeComponent.tsx
  client/src/container/project/Board.tsx
  client/src/container/project/Register.tsx
  client/src/container/sign/FindPw.tsx
  client/src/container/sign/setProfile.tsx
  client/src/container/study/Board.tsx
  client/src/hook/useCheckChat.ts
  client/src/hook/useCheckValidValue.ts
Labels: [FE] 임정렬, [FE] 이예진

#146 [FE] 🔧 59) 프로젝트 스터디 api 연동 3차
  client/src/api/constant.ts
  client/src/api/project/api.ts
  client/src/api/project/hook.ts
  client/src/api/study/api.ts
  client/src/api/study/hook.ts
  client/src/container/main/component/ChangeComponent.tsx
  client/src/container/main/component/ProjectList.tsx
  client/src/container/project/Board.tsx
  client/src/container/project/Details.tsx
  client/src/container/project/Register.tsx
  client/src/type/project/project.req.dto.ts
  client/src/type/project/project.res.dto.ts
Labels: [FE] 이예진

#147 [BE] 🐛 111) 자유,질문,답변,댓글 페이지네이션 오류 수정
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/answer/service/AnswerService.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/comment/service/CommentService.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/infoboard/controller/InfoBoardController.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/infoboard/service/InfoBoardService.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/questionboard/service/QuestionBoardService.java
Labels: [BE] 오동석

#149 [FE] 💄 97) 회원가입 프로필설정 구성
  client/src/App.tsx
  client/src/assets/sign/fg_1.png
  client/src/assets/sign/fg_2.png
  client/src/assets/sign/fg_3.png
  client/src/assets/sign/fg_4.png
  client/src/assets/sign/fg_5.png
  client/src/container/sign/SignUp1.tsx
  client/src/container/sign/SignUp2.tsx
  client/src/container/sign/SignUp3.tsx
  client/src/container/sign/component/SignButton.tsx
  client/src/container/sign/component/SignLayout2.tsx
  client/src/container/sign/setProfile1.tsx
  client/src/container/sign/setProfile2.tsx
  client/src/container/sign/setProfile3.tsx
  client/src/container/sign/setProfile4.tsx
  client/src/container/sign/setProfile5.tsx
Labels: [FE] 손설희

#157 [FE] 🔧 60) 등록페이지 인풋 수정
  client/src/common-component/project-study/Dropdown.tsx
  client/src/common-component/project-study/InputForNumber.tsx
  client/src/container/main/component/ProjectList.tsx
  client/src/container/project/Board.tsx
  client/src/container/project/Register.tsx
  client/src/type/project/common.ts
Labels: [FE] 이예진

#159 [BE] ♻️ 스택태그 반환값 수정
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/stacktag/service/StackTagService.java
Labels: [BE] 오동석

#161 [FE] ♻️ 158) api 연동 3차
  client/package.json
  client/src/App.tsx
  client/src/api/project/api.ts
  client/src/api/project/hook.ts
  client/src/api/project/projectKeyFactory.ts
  client/src/api/study/api.ts
  client/src/api/study/hook.ts
  client/src/api/study/studyKeyFactory.ts
  client/src/common-component/AutoCompletionTags.tsx
  client/src/common-component/Header.tsx
  client/src/common-component/Pagination.tsx
  client/src/common-component/project-study/SkeletonUi.tsx
  client/src/container/info/Board.tsx
  client/src/container/info/component/InfoItem.tsx
  client/src/container/info/component/SearchFilter.tsx
  client/src/container/layout/Layout.tsx
  client/src/container/main/component/ChangeComponent.tsx
  client/src/container/main/component/ProjectList.tsx
  client/src/container/main/component/SkeletonUi.tsx
  client/src/container/mypage/AuthUser.tsx
  client/src/container/mypage/component/UserInfo.tsx
  client/src/container/project/Board.tsx
  client/src/container/project/Register.tsx
  client/src/container/question/Board.tsx
  client/src/container/question/component/QuestionItem.tsx
  client/src/container/sign/Login.tsx
  client/src/container/sign/SetPro.tsx
  client/src/container/sign/SignUp1.tsx
  client/src/container/sign/SignUp2.tsx
  client/src/container/sign/SignUp3.tsx
  client/src/container/sign/component/SignButton.tsx
  client/src/container/sign/setProfile.tsx
  client/src/container/sign/setProfile1.tsx
  client/src/container/sign/setProfile2.tsx
  client/src/container/sign/setProfile3.tsx
  client/src/container/sign/setProfile4.tsx
  client/src/container/sign/setProfile5.tsx
  client/src/container/study/Board.tsx
  client/src/container/study/Register.tsx
  client/src/container/study/component/BoardList.tsx
  client/src/container/todo/TodoList.tsx
  client/src/container/user/List.tsx
  client/src/container/user/component/UserActivity.tsx
  client/src/hook/useLogInAndOut.ts
  client/src/type/project/common.ts
  client/src/type/project/project.req.dto.ts
  client/src/type/project/project.res.dto.ts
  client/src/type/study/study.req.dto.ts
  client/src/type/study/study.res.dto.ts
  client/src/util/pagination-helper.ts
Labels: [FE] 임정렬

#163 [FE] ✨ 162) 드롭다운 구현
  client/src/common-component/project-study/Dropdown.tsx
  client/src/container/project/Register.tsx
Labels: [FE] 이예진

#170 [FE] 💄 169) 모집여부에 따른 화면 변화
  client/src/api/project/api.ts
  client/src/common-component/project-study/Dropdown.tsx
  client/src/container/main/component/ProjectList.tsx
  client/src/container/main/component/StudyList.tsx
  client/src/container/project/Details.tsx
  client/src/container/project/Register.tsx
  client/src/container/project/component/BoardList.tsx
  client/src/container/user/UserDetail.tsx
Labels: [FE] 이예진

#172 [FE] ♻️ 164) 프로젝트, 스터디 조회 및 등록, 수정 데이터 연동 및 리팩토링
  client/.env.example
  client/src/App.tsx
  client/src/api/project/api.ts
  client/src/api/project/hook.ts
  client/src/api/study/api.ts
  client/src/api/study/hook.ts
  client/src/common-component/AutoCompletionTags.tsx
  client/src/container/main/component/ProjectList.tsx
  client/src/container/main/component/StudyList.tsx
  client/src/container/project/Board.tsx
  client/src/container/project/Details.tsx
  client/src/container/project/Register.tsx
  client/src/container/project/component/BoardList.tsx
  client/src/container/project/component/DateChoice.tsx
  client/src/container/project/component/DetailSkeleton.tsx
  client/src/container/sign/Login.tsx
  client/src/container/sign/OauthUser.tsx
  client/src/container/sign/SignUp1.tsx
  client/src/container/study/Board.tsx
  client/src/container/study/Details.tsx
  client/src/container/study/Register.tsx
  client/src/container/study/component/BoardList.tsx
  client/src/container/study/component/DetailSkeleton.tsx
  client/src/container/user/component/UserBlockModal.tsx
  client/src/feature/Global.ts
  client/src/hook/useLogInAndOut.ts
  client/src/type/study/study.req.dto.ts
  client/src/type/study/study.res.dto.ts
Labels: [FE] 임정렬

#179 [FE] 💄 177) 화면 디자인 일부 수정
  client/src/assets/main/board.svg
  client/src/assets/main/board_wide.jpg
  client/src/assets/main/project.svg
  client/src/assets/main/project_wide.jpg
  client/src/assets/main/study.svg
  client/src/assets/main/study_wide.jpg
  client/src/common-component/Navigation.tsx
  client/src/common-component/project-study/InputForNumber.tsx
  client/src/container/info/component/SearchFilter.tsx
  client/src/container/main/component/CarouselCustomNavigation.tsx
  client/src/container/main/component/ProjectList.tsx
  client/src/container/project/Details.tsx
  client/src/container/project/Register.tsx
  client/src/container/study/Register.tsx
  client/src/index.css
  client/src/type/study/study.res.dto.ts
Labels: [FE] 이예진

#180 [BE] ♻️ 답변생성 권한 수정
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/answer/service/AnswerService.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/infoboard/mapper/InfoBoardMapper.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/projectboard/mapper/ProjectMapper.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/questionboard/service/QuestionBoardService.java
  server/DevSquad/src/main/java/WOOMOOL/DevSquad/studyboard/mapper/StudyMapper.java
Labels: [BE] 오동석

#191 [FE] 💄 187) 전반적인 디자인 수정
  client/src/assets/arrowDown.png
  client/src/assets/arrowUp.png
  client/src/common-component/AutoCompletionTags.tsx
  client/src/common-component/Button.tsx
  client/src/common-component/Header.tsx
  client/src/common-component/Input.tsx
  client/src/common-component/Navigation.tsx
  client/src/common-component/Pagination.tsx
  client/src/common-component/Textarea.tsx
  client/src/common-component/Typography.tsx
  client/src/common-component/board/Dropdown.tsx
  client/src/common-component/board/SearchFilters.tsx
  client/src/common-component/board/SearchInput.tsx
  client/src/common-component/project-study/Dropdown.tsx
  client/src/common-component/project-study/Tag.tsx
  client/src/container/main/component/CarouselCustomNavigation.tsx
  client/src/container/main/component/ProjectList.tsx
  client/src/container/main/component/StudyList.tsx
  client/src/container/project/Details.tsx
  client/src/container/project/component/BoardList.tsx
  client/src/container/project/component/DateChoice.tsx
  client/src/container/project/component/DetailSkeleton.tsx
  client/src/container/sign/Login.tsx
  client/src/container/study/Details.tsx
  client/src/container/study/Register.tsx
  client/src/container/study/component/BoardList.tsx
  client/src/container/study/component/DetailSkeleton.tsx
  client/src/container/user/component/UserBlockModal.tsx
  client/src/index.css
  client/src/type/study/study.res.dto.ts
  client/tailwind.config.js
Labels: [FE] 이예진
